### ISSUE TITLE
when is this comming out and will it support 3d formats

### ISSUE THREAD

**Issue by Pickymarker** [gurrrrrrett3/vrchat-jellyfin#1]
when is this comming out and will it support 3d formats

**Comment by gurrrrrrett3** [comment]
I don't really see a way to support 3d formats without a custom player. as for release times not sure yet. Been busy with irl stuff and haven't been working on it much

**Comment by heavygee** [comment]
How about a readme for the config changes necessary, from where things are atm?

**Comment by gurrrrrrett3** [comment]
I can write one later, I've just been too busy with work to get much progress done. I'll see if I can get some progress made in the next couple of weeks, I didn't realize there was an interest in the project at all when I started it

**Comment by gurrrrrrett3** [comment]
made some changes, it should be functional now, can't test because they broke video players on linux again but it should work

**Comment by gurrrrrrett3** [comment]
just tested with two entire movies and a group of friends and everything seems to be working great, feel free to use
