### ISSUE TITLE
It works!, but not grabing all files in all libaries 

### ISSUE THREAD

**Issue by noideaman** [gurrrrrrett3/vrchat-jellyfin#3]
![image](https://github.com/gurrrrrrett3/vrchat-jellyfin/assets/39884745/868353f2-6ef6-45c6-8cf8-054113ecc499)
it seems to not be seeing all video files in libaries

Is there a debug flag?

**Comment by gurrrrrrett3** [comment]
fixed! was an issue with how I handled folders
